apiVersion: v1
kind: Service
metadata:
  name: reservationmanagement
  labels:
    app: reservationmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reservationmanagement