name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./reservationmanagement/pom.xml
          mvn clean package -f ./calendarintegration/pom.xml
          mvn clean package -f ./accesscontrol/pom.xml
          mvn clean package -f ./resourcemanagement/pom.xml
          mvn clean package -f ./statistics/pom.xml
          mvn clean package -f ./roommanagement/pom.xml

      - name: Docker Build and push for Reservationmanagement
        uses: docker/build-push-action@v4
        with:
          context: ./reservationmanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reservationmanagement:latest
            ghcr.io/${{ github.repository }}/reservationmanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for Calendarintegration
        uses: docker/build-push-action@v4
        with:
          context: ./calendarintegration
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/calendarintegration:latest
            ghcr.io/${{ github.repository }}/calendarintegration:${{ github.ref_name }}
            
      - name: Docker Build and push for Accesscontrol
        uses: docker/build-push-action@v4
        with:
          context: ./accesscontrol
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/accesscontrol:latest
            ghcr.io/${{ github.repository }}/accesscontrol:${{ github.ref_name }}
            
      - name: Docker Build and push for Resourcemanagement
        uses: docker/build-push-action@v4
        with:
          context: ./resourcemanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/resourcemanagement:latest
            ghcr.io/${{ github.repository }}/resourcemanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for Statistics
        uses: docker/build-push-action@v4
        with:
          context: ./statistics
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/statistics:latest
            ghcr.io/${{ github.repository }}/statistics:${{ github.ref_name }}
            
      - name: Docker Build and push for Roommanagement
        uses: docker/build-push-action@v4
        with:
          context: ./roommanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/roommanagement:latest
            ghcr.io/${{ github.repository }}/roommanagement:${{ github.ref_name }}
            
