apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcemanagement
  labels:
    app: resourcemanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourcemanagement
  template:
    metadata:
      labels:
        app: resourcemanagement
    spec:
      containers:
        - name: resourcemanagement
          image: "username/resourcemanagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
