apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendarintegration
  labels:
    app: calendarintegration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendarintegration
  template:
    metadata:
      labels:
        app: calendarintegration
    spec:
      containers:
        - name: calendarintegration
          image: "username/calendarintegration:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
