apiVersion: v1
kind: Service
metadata:
  name: calendarintegration
  labels:
    app: calendarintegration
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: calendarintegration