server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: reservationmanagement
          uri: http://localhost:8082
          predicates:
            - Path=/reservations/**, /getMeetingRooms/**
        - id: calendarintegration
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/**, 
        - id: accesscontrol
          uri: http://localhost:8084
          predicates:
            - Path=/users/**, 
        - id: resourcemanagement
          uri: http://localhost:8085
          predicates:
            - Path=/facilityRequests/**, /getFacilities/**
        - id: statistics
          uri: http://localhost:8086
          predicates:
            - Path=/reservationStatistics/**, /facilityStatistics/**, /roomUsages/**, /facilityHistories/**
        - id: roommanagement
          uri: http://localhost:8087
          predicates:
            - Path=/meetingRooms/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservationmanagement
          uri: http://reservationmanagement:8080
          predicates:
            - Path=/reservations/**, 
        - id: calendarintegration
          uri: http://calendarintegration:8080
          predicates:
            - Path=/notifications/**, 
        - id: accesscontrol
          uri: http://accesscontrol:8080
          predicates:
            - Path=/users/**, 
        - id: resourcemanagement
          uri: http://resourcemanagement:8080
          predicates:
            - Path=/facilityRequests/**, 
        - id: statistics
          uri: http://statistics:8080
          predicates:
            - Path=/reservationStatistics/**, /facilityStatistics/**, 
        - id: roommanagement
          uri: http://roommanagement:8080
          predicates:
            - Path=/meetingRooms/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
