---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservationmanagement
  labels:
    app: reservationmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservationmanagement
  template:
    metadata:
      labels:
        app: reservationmanagement
    spec:
      containers:
        - name: reservationmanagement
          image: username/reservationmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendarintegration
  labels:
    app: calendarintegration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendarintegration
  template:
    metadata:
      labels:
        app: calendarintegration
    spec:
      containers:
        - name: calendarintegration
          image: username/calendarintegration:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: accesscontrol
  labels:
    app: accesscontrol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accesscontrol
  template:
    metadata:
      labels:
        app: accesscontrol
    spec:
      containers:
        - name: accesscontrol
          image: username/accesscontrol:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcemanagement
  labels:
    app: resourcemanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourcemanagement
  template:
    metadata:
      labels:
        app: resourcemanagement
    spec:
      containers:
        - name: resourcemanagement
          image: username/resourcemanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics
  labels:
    app: statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics
  template:
    metadata:
      labels:
        app: statistics
    spec:
      containers:
        - name: statistics
          image: username/statistics:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: roommanagement
  labels:
    app: roommanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roommanagement
  template:
    metadata:
      labels:
        app: roommanagement
    spec:
      containers:
        - name: roommanagement
          image: username/roommanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: reservationmanagement
  labels:
    app: reservationmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reservationmanagement


---


apiVersion: v1
kind: Service
metadata:
  name: calendarintegration
  labels:
    app: calendarintegration
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: calendarintegration


---


apiVersion: v1
kind: Service
metadata:
  name: accesscontrol
  labels:
    app: accesscontrol
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: accesscontrol


---


apiVersion: v1
kind: Service
metadata:
  name: resourcemanagement
  labels:
    app: resourcemanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: resourcemanagement


---


apiVersion: v1
kind: Service
metadata:
  name: statistics
  labels:
    app: statistics
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: statistics


---


apiVersion: v1
kind: Service
metadata:
  name: roommanagement
  labels:
    app: roommanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: roommanagement

